spring:
  application:
    name: talk-center
  data:
    mongodb:
      database: c-talk
      host: 192.168.63.187
      port: 27017
      username: root
      password: admin123456!!!
  rabbitmq:
    host: 192.168.63.187
    port: 5672
    username: user
    password: password
    virtual-host: /

server:
  port: 1002
  servlet:
    encoding:
      force: true
      charset: utf-8

# snowflake id生成
snowflake:
  data-center: 1
  worker: 1

# websocket服务器配置
ws:
  server:
    port: 1003
    host: 0.0.0.0

#minio 配置
minio:
  endpoint: http://http://192.168.63.187:9000
  bucke-name: pic
  access-key: minioadmin
  secret-key: minioadmin