name: CI Maven push on docker
on:
  workflow_dispatch:
  push:
    branches:
      - pro
      
jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # maven build
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn install -DskipTests=true
      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"
      - name: release
        uses: actions/upload-artifact@v4
        with:
          name: c-talk-backend
          path: ./target/*.jar
      - name: Build Docker Image
        run: docker compose  -f ./docker/docker-compose.yml build
      - name: Publish Docker Image
        run: docker compose  -f ./docker/docker-compose.yml push
